site_name: Total Economy Docs
theme:
  name: material
  palette:
    scheme: slate
markdown_extensions:
    - toc:
        toc_depth: 0
nav:
  - Installation: 'index.md'
  - Storage: 'storage.md'
  - Development:
    - Testing: 'developers/testing.md'